# Generated by Django 3.2 on 2021-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='pic',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='supersubtopic',
            name='pic',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pic',
            field=models.URLField(),
        ),
    ]
