# Generated by Django 3.2 on 2021-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210514_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='subTopic',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='SuperSubTopic',
        ),
    ]
