# Generated by Django 3.2 on 2021-05-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210524_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='pic',
        ),
    ]
