# Generated by Django 3.2 on 2021-06-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
