# Generated by Django 3.2 on 2021-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='newResourceTitle',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
